/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FourftImport } from './routes/_fourft'
import { Route as IndexImport } from './routes/index'
import { Route as DatasetDatasetsImport } from './routes/_dataset.datasets'
import { Route as FourftFourftIndexImport } from './routes/_fourft.fourft.index'
import { Route as FourftFourftFourftIdImport } from './routes/_fourft.fourft.$fourftId'
import { Route as FourftFourftCreateIndexImport } from './routes/_fourft.fourft.create.index'

// Create/Update Routes

const FourftRoute = FourftImport.update({
  id: '/_fourft',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DatasetDatasetsRoute = DatasetDatasetsImport.update({
  id: '/_dataset/datasets',
  path: '/datasets',
  getParentRoute: () => rootRoute,
} as any)

const FourftFourftIndexRoute = FourftFourftIndexImport.update({
  id: '/fourft/',
  path: '/fourft/',
  getParentRoute: () => FourftRoute,
} as any)

const FourftFourftFourftIdRoute = FourftFourftFourftIdImport.update({
  id: '/fourft/$fourftId',
  path: '/fourft/$fourftId',
  getParentRoute: () => FourftRoute,
} as any)

const FourftFourftCreateIndexRoute = FourftFourftCreateIndexImport.update({
  id: '/fourft/create/',
  path: '/fourft/create/',
  getParentRoute: () => FourftRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_fourft': {
      id: '/_fourft'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof FourftImport
      parentRoute: typeof rootRoute
    }
    '/_dataset/datasets': {
      id: '/_dataset/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetDatasetsImport
      parentRoute: typeof rootRoute
    }
    '/_fourft/fourft/$fourftId': {
      id: '/_fourft/fourft/$fourftId'
      path: '/fourft/$fourftId'
      fullPath: '/fourft/$fourftId'
      preLoaderRoute: typeof FourftFourftFourftIdImport
      parentRoute: typeof FourftImport
    }
    '/_fourft/fourft/': {
      id: '/_fourft/fourft/'
      path: '/fourft'
      fullPath: '/fourft'
      preLoaderRoute: typeof FourftFourftIndexImport
      parentRoute: typeof FourftImport
    }
    '/_fourft/fourft/create/': {
      id: '/_fourft/fourft/create/'
      path: '/fourft/create'
      fullPath: '/fourft/create'
      preLoaderRoute: typeof FourftFourftCreateIndexImport
      parentRoute: typeof FourftImport
    }
  }
}

// Create and export the route tree

interface FourftRouteChildren {
  FourftFourftFourftIdRoute: typeof FourftFourftFourftIdRoute
  FourftFourftIndexRoute: typeof FourftFourftIndexRoute
  FourftFourftCreateIndexRoute: typeof FourftFourftCreateIndexRoute
}

const FourftRouteChildren: FourftRouteChildren = {
  FourftFourftFourftIdRoute: FourftFourftFourftIdRoute,
  FourftFourftIndexRoute: FourftFourftIndexRoute,
  FourftFourftCreateIndexRoute: FourftFourftCreateIndexRoute,
}

const FourftRouteWithChildren =
  FourftRoute._addFileChildren(FourftRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof FourftRouteWithChildren
  '/datasets': typeof DatasetDatasetsRoute
  '/fourft/$fourftId': typeof FourftFourftFourftIdRoute
  '/fourft': typeof FourftFourftIndexRoute
  '/fourft/create': typeof FourftFourftCreateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof FourftRouteWithChildren
  '/datasets': typeof DatasetDatasetsRoute
  '/fourft/$fourftId': typeof FourftFourftFourftIdRoute
  '/fourft': typeof FourftFourftIndexRoute
  '/fourft/create': typeof FourftFourftCreateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_fourft': typeof FourftRouteWithChildren
  '/_dataset/datasets': typeof DatasetDatasetsRoute
  '/_fourft/fourft/$fourftId': typeof FourftFourftFourftIdRoute
  '/_fourft/fourft/': typeof FourftFourftIndexRoute
  '/_fourft/fourft/create/': typeof FourftFourftCreateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/datasets'
    | '/fourft/$fourftId'
    | '/fourft'
    | '/fourft/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/datasets'
    | '/fourft/$fourftId'
    | '/fourft'
    | '/fourft/create'
  id:
    | '__root__'
    | '/'
    | '/_fourft'
    | '/_dataset/datasets'
    | '/_fourft/fourft/$fourftId'
    | '/_fourft/fourft/'
    | '/_fourft/fourft/create/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FourftRoute: typeof FourftRouteWithChildren
  DatasetDatasetsRoute: typeof DatasetDatasetsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FourftRoute: FourftRouteWithChildren,
  DatasetDatasetsRoute: DatasetDatasetsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_fourft",
        "/_dataset/datasets"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_fourft": {
      "filePath": "_fourft.tsx",
      "children": [
        "/_fourft/fourft/$fourftId",
        "/_fourft/fourft/",
        "/_fourft/fourft/create/"
      ]
    },
    "/_dataset/datasets": {
      "filePath": "_dataset.datasets.tsx"
    },
    "/_fourft/fourft/$fourftId": {
      "filePath": "_fourft.fourft.$fourftId.tsx",
      "parent": "/_fourft"
    },
    "/_fourft/fourft/": {
      "filePath": "_fourft.fourft.index.tsx",
      "parent": "/_fourft"
    },
    "/_fourft/fourft/create/": {
      "filePath": "_fourft.fourft.create.index.tsx",
      "parent": "/_fourft"
    }
  }
}
ROUTE_MANIFEST_END */
