/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as DatasetsImport } from './routes/datasets';
import { Route as IndexImport } from './routes/index';
import { Route as FourftFourftIdImport } from './routes/fourft.$fourftId';
import { Route as FourftCreateIndexImport } from './routes/fourft.create.index';

// Create/Update Routes

const DatasetsRoute = DatasetsImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const FourftFourftIdRoute = FourftFourftIdImport.update({
  id: '/fourft/$fourftId',
  path: '/fourft/$fourftId',
  getParentRoute: () => rootRoute,
} as any);

const FourftCreateIndexRoute = FourftCreateIndexImport.update({
  id: '/fourft/create/',
  path: '/fourft/create/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/datasets': {
      id: '/datasets';
      path: '/datasets';
      fullPath: '/datasets';
      preLoaderRoute: typeof DatasetsImport;
      parentRoute: typeof rootRoute;
    };
    '/fourft/$fourftId': {
      id: '/fourft/$fourftId';
      path: '/fourft/$fourftId';
      fullPath: '/fourft/$fourftId';
      preLoaderRoute: typeof FourftFourftIdImport;
      parentRoute: typeof rootRoute;
    };
    '/fourft/create/': {
      id: '/fourft/create/';
      path: '/fourft/create';
      fullPath: '/fourft/create';
      preLoaderRoute: typeof FourftCreateIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/datasets': typeof DatasetsRoute;
  '/fourft/$fourftId': typeof FourftFourftIdRoute;
  '/fourft/create': typeof FourftCreateIndexRoute;
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/datasets': typeof DatasetsRoute;
  '/fourft/$fourftId': typeof FourftFourftIdRoute;
  '/fourft/create': typeof FourftCreateIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/': typeof IndexRoute;
  '/datasets': typeof DatasetsRoute;
  '/fourft/$fourftId': typeof FourftFourftIdRoute;
  '/fourft/create/': typeof FourftCreateIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/datasets' | '/fourft/$fourftId' | '/fourft/create';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/datasets' | '/fourft/$fourftId' | '/fourft/create';
  id: '__root__' | '/' | '/datasets' | '/fourft/$fourftId' | '/fourft/create/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DatasetsRoute: typeof DatasetsRoute;
  FourftFourftIdRoute: typeof FourftFourftIdRoute;
  FourftCreateIndexRoute: typeof FourftCreateIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsRoute: DatasetsRoute,
  FourftFourftIdRoute: FourftFourftIdRoute,
  FourftCreateIndexRoute: FourftCreateIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/datasets",
        "/fourft/$fourftId",
        "/fourft/create/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/datasets": {
      "filePath": "datasets.tsx"
    },
    "/fourft/$fourftId": {
      "filePath": "fourft.$fourftId.tsx"
    },
    "/fourft/create/": {
      "filePath": "fourft.create.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
