# Generated by Django 5.0.4 on 2025-01-22 16:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clever_miner_api', '0003_dataset_columns_count_dataset_delimiter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourFtResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('base', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('relbase', models.FloatField(blank=True, null=True)),
                ('aad', models.FloatField(blank=True, null=True)),
                ('ante_min_len', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('ante_max_len', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('succe_min_len', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('succe_max_len', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)])),
                ('con_dis_antecedent_type', models.CharField(max_length=256)),
                ('con_dis_succedent_type', models.CharField(max_length=256)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='four_ft_results', to='clever_miner_api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Cedent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('min_len', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('max_len', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('role', models.CharField(choices=[('antecedent', 'Antecedent'), ('succedent', 'Succedent')], max_length=10)),
                ('four_ft_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cedents', to='clever_miner_api.fourftresult')),
            ],
        ),
    ]
