# Generated by Django 5.0.4 on 2025-02-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clever_miner_api', '0004_fourftresult_cedent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourftresult',
            name='s3_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
