# Generated by Django 5.0.2 on 2024-04-08 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clever_miner_api', '0009_storagefile_remove_dataset_s3_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fourftresult',
            name='con_dis_condition_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='fourftresult',
            name='cond_min_len',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)]),
        ),
        migrations.AddField(
            model_name='fourftresult',
            name='cond_max_len',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(128)]),
        ),
    ] 